Models/Map.cs
namespace ie_sport_injury_ver_1._3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Map")]
    public partial class Map
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string Description { get; set; }

        [Column(TypeName = "numeric")]
        public decimal Latitude { get; set; }

        [Column(TypeName = "numeric")]
        public decimal Longitude { get; set; }

        [Column(TypeName = "numeric")]
        public decimal PostCode { get; set; }

        [Required]
        public string NodeType { get; set; }

        [Required]
        public string Week { get; set; }

        [Required]
        public string AccidentType { get; set; }

        [Column(TypeName = "timestamp")]
        [MaxLength(8)]
        [Timestamp]
        public byte[] Time { get; set; }

        [Column(TypeName = "numeric")]
        public decimal Month { get; set; }
    }
}

Models/Quiz.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ie_sport_injury_ver_1._3.Models
{
    public class Quiz
    {
    }
}

Controllers/AnalysisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ie_sport_injury_ver_1._3.Controllers
{
    public class AnalysisController : Controller
    {
        public ActionResult Index()
        {
            return View ();
        }
    }
}

Controllers/EducationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ie_sport_injury_ver_1._3.Controllers
{
    public class EducationController : Controller
    {
        public ActionResult Index()
        {
            return View ();
        }

        public ActionResult EssentialRoadRules()
        {
            return View();
        }

        public ActionResult RidingInTraffic()
        {
            return View();
        }

        public ActionResult RidingLanesAndPaths()
        {
            return View();
        }

        public ActionResult BikeComponents()
        {
            return View();
        }

        public ActionResult WearingHelmet()
        {
            return View();
        }

        public ActionResult TrafficSigns()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ie_sport_injury_ver_1._3.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Education()
        {
            ViewBag.Message = "Your education page.";

            return View();
        }

        public ActionResult Quiz()
        {
            ViewBag.Message = "Your quiz page.";

            return View();
        }

        public ActionResult WarmUp()
        {
            ViewBag.Message = "Your WarmUp page.";

            return View();
        }

        public ActionResult Map()
        {
            ViewBag.Message = "Your Map page.";

            return View();
        }

        public ActionResult RoadRules()
        {
            ViewBag.Message = "Your Article page.";

            return View();
        }
    }
}

Controllers/MapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ie_sport_injury_ver_1._3.Controllers
{
    public class MapController : Controller
    {
        public ActionResult Index()
        {
            return View ();
        }
    }
}

Controllers/MapsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using ie_sport_injury_ver_1._3.Models;

namespace ie_sport_injury_ver_1._3.Controllers
{
    public class MapsController : ApiController
    {
        private map_model db = new map_model();

        // GET: api/Maps
        public IQueryable<Map> GetMaps()
        {
            return db.Maps;
        }

        // GET: api/Maps/5
        [ResponseType(typeof(Map))]
        public IHttpActionResult GetMap(int id)
        {
            Map map = db.Maps.Find(id);
            if (map == null)
            {
                return NotFound();
            }

            return Ok(map);
        }

        // PUT: api/Maps/5
        [ResponseType(typeof(void))]
        public IHttpActionResult PutMap(int id, Map map)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != map.Id)
            {
                return BadRequest();
            }

            db.Entry(map).State = EntityState.Modified;

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!MapExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/Maps
        [ResponseType(typeof(Map))]
        public IHttpActionResult PostMap(Map map)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            db.Maps.Add(map);

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateException)
            {
                if (MapExists(map.Id))
                {
                    return Conflict();
                }
                else
                {
                    throw;
                }
            }

            return CreatedAtRoute("DefaultApi", new { id = map.Id }, map);
        }

        // DELETE: api/Maps/5
        [ResponseType(typeof(Map))]
        public IHttpActionResult DeleteMap(int id)
        {
            Map map = db.Maps.Find(id);
            if (map == null)
            {
                return NotFound();
            }

            db.Maps.Remove(map);
            db.SaveChanges();

            return Ok(map);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool MapExists(int id)
        {
            return db.Maps.Count(e => e.Id == id) > 0;
        }
    }
}

Controllers/NavigationMapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ie_sport_injury_ver_1._3.Controllers
{
    public class NavigationMapController : Controller
    {
        // GET: NavigationMap
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/QuizIndexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ie_sport_injury_ver_1._3.Controllers
{
    public class QuizIndexController : Controller
    {
        // GET: QuizIndex
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult BicycleEquipmentQuiz()
        {
            return View();
        }

        public ActionResult RoadRuleQuiz()
        {
            return View();
        }

        public ActionResult TrafficSignQuiz()
        {
            return View();
        }
    }
}

Controllers/WarmUpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ie_sport_injury_ver_1._3.Controllers
{
    public class WarmUpController : Controller
    {
        public ActionResult Index()
        {
            return View ();
        }
    }
}

Controllers/injuryHoverController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ie_sport_injury_ver_1._3.Controllers
{
    public class InjuryHoverController : Controller
    {
        // GET: InjuryHover
        public ActionResult Index()
        {
            return View();
        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

@*<div background-size:cover>*@


@*<img src="~/Views/image2/meet_our_crews.jpg"  width: 100vw; height: 80vh;  alt="test" />*@
@*<img src=" https://nascar.nbcsports.com/wp-content/uploads/sites/9/2019/05/img_1965-e1558468046501.jpeg?resize=1024,575" />*@
@*<span style="width:920px; height:920px; line-height:12px; position:absolute; top:50%; left:50%; margin-left:-420px; margin-top:-160px;color:snow;font-size:590%;font-family:sans-serif">MEET OUR CREWS</span>*@
@*<img src" https: //c1.hoopchina.com.cn/uploads/star/event/images/200217/697bd1b1fce24b92a646c8d1eafef674e847d4a8.jpg" />
    <img src="https://doc-0c-58-docs.googleusercontent.com/docs/securesc/qtdk277ndqoupjlhsvhpo87f7efo51pu/3l9s18q83br2vp6am8d8vlhukndjp5cu/1586761800000/07913430937656289696/07913430937656289696/1haxKWzrbxv_Np19j-mNUBBMdxi63V53m?e=download&h=13390630169452005924&authuser=0&nonce=mnk9pvn0rpv84&user=079134309376562">*@

<div class="header1">
    <a href="#" class="btn-white">Learn More</a>
</div>
@*<p><a href="zliu0054@student.monash.edu" class="btn btn-primary btn-lg">CONTACT US &raquo;</a></p>
    </div>*@

<div style="background-color:#E8E8E8;word-wrap:break-word;">
    <p style="text-align:center;font-family:sans-serif; font-size:xx-large">
        Introduction
    </p>
</div>

<div style="background-color:#E8E8E8;word-wrap:break-word;">
    <p style="text-align:center;font-family:sans-serif; font-size:xx-large">
        Team strengths :  Diverse technical and cultural background, Innovative, proactive, Goal-oriented.
    </p>
</div>

<div class=" row">
    <img src="https://i.pinimg.com/474x/7d/d3/e3/7dd3e31662f2d76b52abf1b9f9cceffc--office-interior-design-office-interiors.jpg" class="cover" width="1080" height="163" />

</div>

<div class="  row">
    <p style="text-align:center;font-family:sans-serif; font-size:xx-large">
        Meet The Team
    </p>
</div>

<div class="row ">
    <div class="col-md-4">
        <img src="https://st2.depositphotos.com/8448998/11336/i/950/depositphotos_113366320-stock-photo-half-length-portrait-of-young.jpg" class="cover" width="300" height="300" />
        <p style="text-align:center;font-family:sans-serif; font-size:xx-large;color:#8B008B">
            Zexi Liu
        </p>

        <p style="text-align:center;font-family:sans-serif; font-size:larger">
            Programmer
        </p>

        <div align="left" align="left" style="float:left">
            <p><a href="zliu0054@student.monash.edu" class="btn btn-primary btn-lg" ;display:inline-block;>Mail&raquo;</a></p>
        </div>

        <div align="right">
            <p><a href="zliu0054@student.monash.edu" class="btn btn-primary btn-lg" ;display:inline-block;>Mail&raquo;</a></p>
        </div>
    </div>

    <div class="col-md-4">
        <img src="https://st2.depositphotos.com/8448998/11336/i/950/depositphotos_113366320-stock-photo-half-length-portrait-of-young.jpg" class="cover" width="300" height="300" />
        <p style="text-align:center;font-family:sans-serif; font-size:xx-large;color:#8B008B">
            Khawar Mehmood
        </p>

        <p style="text-align:center;font-family:sans-serif; font-size:larger">
            Tutor
        </p>

        <div align="left" align="left" style="float:left">
            <p><a href="zliu0054@student.monash.edu" class="btn btn-primary btn-lg" ;display:inline-block;>Mail&raquo;</a></p>
        </div>

        <div align="right">
            <p><a href="zliu0054@student.monash.edu" class="btn btn-primary btn-lg" ;display:inline-block;>Mail&raquo;</a></p>
        </div>
    </div>

    <div class="col-md-4">
        <img src="https://st2.depositphotos.com/8448998/11336/i/950/depositphotos_113366320-stock-photo-half-length-portrait-of-young.jpg" class="cover" width="300" height="300" />
        <p style="text-align:center;font-family:sans-serif; font-size:xx-large;color:#8B008B">
            Rohan
        </p>

        <p style="text-align:center;font-family:sans-serif; font-size:larger">
            Data scientist
        </p>

        <div align="left" align="left" style="float:left">
            <p><a href="zliu0054@student.monash.edu" class="btn btn-primary btn-lg" ;display:inline-block;>Mail&raquo;</a></p>
        </div>

        <div align="right">
            <p><a href="zliu0054@student.monash.edu" class="btn btn-primary btn-lg" ;display:inline-block;>Mail&raquo;</a></p>
        </div>
    </div>

</div>


<div class="row ">
    <div class="col-md-4">
        <img src="https://st2.depositphotos.com/8448998/11336/i/950/depositphotos_113366320-stock-photo-half-length-portrait-of-young.jpg" class="cover" width="300" height="300" />
        <p style="text-align:center;font-family:sans-serif; font-size:xx-large;color:#8B008B">
            Haixin Mo
        </p>

        <p style="text-align:center;font-family:sans-serif; font-size:larger">
            Business analysist
        </p>

        <div align="left" align="left" style="float:left">
            <p><a href="zliu0054@student.monash.edu" class="btn btn-primary btn-lg" ;display:inline-block;>Mail&raquo;</a></p>
        </div>

        <div align="right">
            <p><a href="zliu0054@student.monash.edu" class="btn btn-primary btn-lg" ;display:inline-block;>Mail&raquo;</a></p>
        </div>
    </div>

    <div class="col-md-4">
        <img src="https://st2.depositphotos.com/8448998/11336/i/950/depositphotos_113366320-stock-photo-half-length-portrait-of-young.jpg" class="cover" width="300" height="300" />
        <p style="text-align:center;font-family:sans-serif; font-size:xx-large;color:#8B008B">
            Mohammad Bhuyan
        </p>

        <p style="text-align:center;font-family:sans-serif; font-size:larger">
            Tech Tutor
        </p>

        <div align="left" align="left" style="float:left">
            <p><a href="zliu0054@student.monash.edu" class="btn btn-primary btn-lg" ;display:inline-block;>Mail&raquo;</a></p>
        </div>

        <div align="right">
            <p><a href="zliu0054@student.monash.edu" class="btn btn-primary btn-lg" ;display:inline-block;>Mail&raquo;</a></p>
        </div>
    </div>

    <div class="col-md-4">
        <img src="https://st2.depositphotos.com/8448998/11336/i/950/depositphotos_113366320-stock-photo-half-length-portrait-of-young.jpg" class="cover" width="300" height="300" />
        <p style="text-align:center;font-family:sans-serif; font-size:xx-large;color:#8B008B">
            Fang-I Lee
        </p>

        <p style="text-align:center;font-family:sans-serif; font-size:larger">
            Programmer
        </p>

        <div align="left" align="left" style="float:left">
            <p><a href="zliu0054@student.monash.edu" class="btn btn-primary btn-lg" ;display:inline-block;>Mail&raquo;</a></p>
        </div>

        <div align="right">
            <p><a href="zliu0054@student.monash.edu" class="btn btn-primary btn-lg" ;display:inline-block;>Mail&raquo;</a></p>
        </div>
    </div>

</div>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    ViewBag.BodyStyle = "";
}
    <script type="text/javascript">loopy()
    function loopy() {
        var sWord = ""
        while (sWord != "29") {
            sWord = prompt("Please enter password")
        }
        alert("Welcome")
    }</script>

    <section id="home" class="main-banner parallaxie" style="background: url('/Content/images/bg2.jpg')">
        <div class="heading">
            <h1>Say no to injuries</h1>
            <h3 class="cd-headline clip is-full-width">
                <span>Cycling </span>
                <span class="cd-words-wrapper">
                    <b class="is-visible">Safest</b>
                    <b>Healthiest</b>
                </span>
                <div class="btn-ber">
                    <a class="get_btn btn-hover-new" href="@Url.Action("Index", "Education")">Learn More</a>
                    <!--<a class="learn_btn hvr-bounce-to-top" href="#">Cycling Map</a>-->
                </div>
            </h3>
        </div>
    </section>

    <div id="services" class="section lb">
        <div class="container">
            <div class="section-title text-center">
                <h3>Sportsaholics</h3>
                <p>Start your cycling journey.</p>
            </div>
            <!-- end title -->

            <div class="row">
                <div class="col-md-4">
                    <a href="@Url.Action("Index", "Education")">
                        <div class="services-inner-box">
                            <div class="ser-icon">
                                <i class="flaticon-books"></i>
                            </div>
                            <h2>Education</h2>
                            <p>Things you need to know before riding your bicycle.</p>
                        </div>
                    </a>
                </div><!-- end col -->
                <div class="col-md-4">
                    <a href="@Url.Action("Index", "InjuryHover")">
                        <div class="services-inner-box">
                            <div class="ser-icon">
                                <i class="flaticon-bandage"></i>
                            </div>
                            <h2>Common Injuries</h2>
                            <p>
                                Get to know the causes of common cycling injuries.
                            </p>
                        </div>
                    </a>
                </div><!-- end col -->
                <div class="col-md-4">
                    <a href="@Url.Action("Index", "NavigationMap")">
                        <div class="services-inner-box">
                            <div class="ser-icon">
                                <i class="flaticon-map"></i>
                            </div>
                            <h2>Navigation Map</h2>
                            <p>
                                Get the safest path to your destination and visualize the bike lanes in the city.
                            </p>
                        </div>
                    </a>
                </div><!-- end col -->
                <div class="col-md-4">
                    <a href="@Url.Action("Index", "QuizIndex")">
                        <div class="services-inner-box">
                            <div class="ser-icon">
                                <i class="flaticon-exam-1"></i>
                            </div>
                            <h2>Trivia</h2>
                            <p>Test your knowledge of bicycle equipment and road rules.</p>
                        </div>
                    </a>
                </div><!-- end col -->
                <div class="col-md-4">
                    <a href="@Url.Action("Index", "Analysis")">
                        <div class="services-inner-box">
                            <div class="ser-icon">
                                <i class="flaticon-computer"></i>
                            </div>
                            <h2>Crash: When & Where</h2>
                            <p>
                                Visualize the safest time and days of week for riding in top 10 crash prone cities of Victoria.
                            </p>
                        </div>
                    </a>
                </div><!-- end col -->
                <div class="col-md-4">
                    <a href="@Url.Action("Index", "Map")">
                        <div class="services-inner-box">
                            <div class="ser-icon">
                                <i class="flaticon-gps"></i>
                            </div>
                            <h2>Crash Map</h2>
                            <p>This map shows all the bicycle crashes that happened across Victoria from 2013 to 2019. </p>
                        </div>
                    </a>
                </div><!-- end col -->

            </div><!-- end row -->
        </div><!-- end container -->
    </div><!-- end section -->

Views/Home/Map.cshtml
@{
    ViewBag.Title = "Map";
    ViewBag.BodyStyle = "body-no-banner";
}

    <div id="portfolio" class="section lb">
        <div class="container">
            <div class="section-title text-center">
                <h3>Map</h3>
                <p>Quisque eget nisl id nulla sagittis auctor quis id. Aliquam quis vehicula enim, non aliquam risus.</p>
            </div><!-- end title -->

            <div class='tableauPlaceholder' id='viz1587969022603' style='position: relative'><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;SJ&#47;SJ7Q9DHTM&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz' style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='path' value='shared&#47;SJ7Q9DHTM' /> <param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;SJ&#47;SJ7Q9DHTM&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='filter' value='publish=yes' /></object></div>
            <script type='text/javascript'>var divElement = document.getElementById('viz1587969022603');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='110%';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);</script>

        </div>
    </div>

Views/Home/PasswordPage.cshtml
@{
    ViewBag.Title = "PasswordPage";
    Layout = "~/Views/Shared/_Layout.cshtml";
        ViewBag.BodyStyle = "body-no-banner";
}
    <script type="text/javascript">loopy()
        function loopy() {
            var sWord = ""
            while (sWord != "sportsaholics") {
                sWord = prompt("Please enter password")
            }
            alert("Welcome")
        }</script>
<h2>PasswordPage</h2>

Views/Home/QuizIndex.cshtml
@{
    ViewBag.Title = "QuizIndex";
    ViewBag.BodyStyle = "body-no-banner";
}

<div id="portfolio" class="section lb">
    <div class="container">
        <div class="section-title text-center">
            <h3>Map</h3>
            <p>Quisque eget nisl id nulla sagittis auctor quis id. Aliquam quis vehicula enim, non aliquam risus.</p>
        </div><!-- end title -->

        <div class="row">
            <div class="col-md-12">
                <img style="max-width: 100%;" src="https://ieimage.s3-ap-southeast-2.amazonaws.com/maptab.png " />
            </div>
        </div>

    </div>
</div>

Views/Home/RoadRules.cshtml
@{
    ViewBag.Title = "RoadRules";
    ViewBag.BodyStyle = "body-no-banner";

}

    <div id="portfolio" class="section lb">
        <div class="container">
            <div class="section-title text-center">
                <h3>Education</h3>
                <p>Something you need to know before your riding.</p>
            </div><!-- end title -->

            <div id="about" class="section wb">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="message-box">
                                <h2>Essential Road Rules</h2>
                                <p> by VicRoads </p>
                                <hr>
                                <h3>| Safe Riding </h3>
                                <p>
                                    When you are riding your bike you must:
                                    <br>• face forwards and have at least one hand on the handlebars.
                                    <br>• keep a safe distance between you and any traffic in front of you.
                                    <br>Make sure you have enough space to stop safely.
                                    <br>‘Drinking’ is against the law. Passengers can only sit on your bike if they are in a seat for a passenger.
                                </p>
                                <h3>| Traffic lights, signals and signs </h3>
                                <p>
                                    You must obey traffic lights, signals, signs and road markings, and follow the road rules on stopping and giving way.
                                    If there are no traffic lights, signs or lines at an intersection, you must give way to any vehicle on your right that would cross your path.
                                </p>

                            </div><!-- end messagebox -->
                        </div><!-- end col -->

                        <div class="col-md-6">
                            <div class="right-box-pro wow fadeIn">
                                <img src="~/Content/images/article_photo/photo_06.png" alt="" class="img-fluid img-rounded">
                            </div><!-- end media -->
                        </div><!-- end col -->
                    </div><!-- end row -->

                    <div class="row">

                        <div class="col-md-2 text-center">
                            <i class="fa fa-bicycle" style="font-size: 80px;"></i>
                        </div><!-- end col -->

                        <div class="col-md-8">
                            <h3>Safely opening car doors</h3>
                            <p>Test</p>
                        </div><!-- end col -->
                    </div><!-- end row -->

                </div><!-- end container -->
            </div><!-- end section -->

        </div>
    </div>

Views/Home/WarmUp.cshtml
@{
    ViewBag.Title = "WarmUp";
    ViewBag.BodyStyle = "body-no-banner";
}

<div id="portfolio" class="section lb">
    <div class="container">
        <div class="section-title text-center">
            <h3>Warm-Up</h3>
            <p>Quisque eget nisl id nulla sagittis auctor quis id. Aliquam quis vehicula enim, non aliquam risus.</p>
        </div><!-- end title -->

        <div class="row">
            <div class="col-md-12">
                <img src=" https://i.pinimg.com/474x/f1/94/cb/f194cbec16b7d8f1493b43ddbc7309dc.jpg" />
            </div>
        </div>

    </div>
</div>