Controllers/EducationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ie_sport_injury_ver_1._3.Controllers
{
    public class EducationController : Controller
    {
        public ActionResult Index()
        {
            return View ();
        }

        public ActionResult EssentialRoadRules()
        {
            return View();
        }

        public ActionResult RidingInTraffic()
        {
            return View();
        }

        public ActionResult RidingLanesAndPaths()
        {
            return View();
        }

        public ActionResult BikeComponents()
        {
            return View();
        }

        public ActionResult WearingHelmet()
        {
            return View();
        }

        public ActionResult TrafficSigns()
        {
            return View();
        }
    }
}

Controllers/streetViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ie_sport_injury_ver_1._3.Controllers
{
    public class StreetViewController : Controller
    {
        // GET: StreetView
        public ActionResult Index()
        {
            return View();
        }
    }
}

Views/Education/BikeComponents.cshtml
@{
    ViewBag.Title = "BikeComponents";
    ViewBag.BodyStyle = "body-no-banner";


}

<div id="article" class="section lb">
    <div class="container">
        <div class="section-title text-center">
            <h3>Education</h3>
            <p>Something you need to know before start your riding.</p>
        </div><!-- end title -->

        <div id="content" class="section wb">
            <div class="container">
                <div class="row mb-4">
                    <div class="col-md-1"></div>
                    <div class="col-md-10">
                        <div class="message-box">
                            <h2>Introduction: Bike Components for Beginners</h2>
                            <p> by Century Cycles </p>
                            <hr>
                            <p>
                                From our perspective, sometimes it’s hard to tell when we’re using everyday language and when we’re slipping into technical jargon. We have to really ask questions to make sure we’re on the same page with a customer and really understand what they are looking for, and often it’s just a matter of making sure we agree on the meaning of the words we are using. For example, we sometimes get people asking for a “wheel,” when all they really need is a new tire. On the other hand, we’ve gotten really perplexed looks when we’ve handed somebody a “rim,” when they were really looking for an entire wheel.
                                <br>So, breaking down the language barrier is an important step in productive relationships between bike shop customers and bike shop employees. To that end, here is a glossary providing a breakdown of the anatomy of the bicycle.
                                Scroll down to the bottom of this page for a video overview of most major bike parts.
                            </p>

                        </div><!-- end messagebox -->
                    </div><!-- end col -->
                </div><!-- end row -->


                <div class="row mb-4">
                    <div class="col-md-1"></div>
                    <div class="col-md-10">
                        <div class="wow fadeIn">
                            <img src="~/Content/images/article_photo/photo_15.png" alt="" class="img-fluid">
                        </div><!-- end media -->
                    </div>
                </div><!-- end row -->


                <div class="row mb-4">
                    <div class="col-md-1"></div>
                    <div class="col-md-10">
                        <div class="message-box">
                            <h5>Bar ends</h5>
                            <p>
                                The angled extensions attached to the ends of some flat handlebars and riser handlebars that provide an alternate place to rest your hands.
                            </p>
                            <h5>Bottom bracket</h5>
                            <p>
                                The collection of ball bearings and spindle housed within the bottom bracket shell of the frame, which provides the “shaft” mechanism on which the crank arms turn.
                            </p>
                            <h5>Braze-ons</h5>
                            <p>
                                Threaded sockets that may or may not be present on the bike frame that provide a place to attach accessories such as bottle cages, cargo racks, and fenders.
                            </p>
                            <h5>Cage</h5>
                            <p>
                                The preferred fancy name for water bottle holder.
                            </p>
                            <h5>Cassette</h5>
                            <p>
                                The collection of gears that is attached to the rear wheel on most modern bicycles (see “Freewheel”).
                            </p>
                            <h5>Chainrings</h5>
                            <p>
                                The gears that are attached to the right-hand crank arm nearer to the front of the bike. A bike with two chainrings is said to have a “double crank;” a bike with three chainrings is said to have a “triple crank.”
                            </p>
                            <h5>Cog</h5>
                            <p>
                                A single gear on a cassette or freewheel gear cluster, or the single rear gear on a fixed-gear bike.
                            </p>
                            <h5>Crank arms</h5>
                            <p>
                                The pedals screw into these; these bolt onto the bottom bracket spindle.
                            </p>
                            <h5>Cyclocomputer</h5>
                            <p>
                                The preferred fancy word for an electronic speedometer/odometer.
                            </p>
                            <h5>Derailer</h5>
                            <p>
                                The device that is bolted to the frame that handles the job of moving the chain from one gear to another when you shift gears. The front derailer handles the shifting on your chainrings and is usually controlled by your left-hand shifter. The rear derailer handles the shifting on your cassette or freewheel, and is usually controlled by your right-hand shifter.
                            </p>
                            <h5>Derailer hanger</h5>
                            <p>
                                A part of the frame where the rear derailleur is attached. It is usually an integrated part of the frame on steel and titanium bikes, but is a separate, replaceable piece on aluminum and carbon fiber bikes.
                            </p>
                            <h5>Drop bar</h5>
                            <p>
                                The type of handlebar found on road racing bikes, with the half-circle-shaped curved ends that extend below the top, flatter part of the bar.
                            </p>
                            <h5>Dropouts</h5>
                            <p>
                                The U-shaped notches at the rear of the bike frame, and at the bottom ends of the front fork legs, where the wheels are held in place. So-called because if you loosen the bolts holding a wheel in place, the wheel “drops out.”
                            </p>
                            <h5>Fixed gear</h5>
                            <p>
                                A type of bicycle that has a single gear and does not have a freewheel or cassette/freehub mechanism, so you are unable to coast. If the wheels are moving, you have to be pedaling. “Fixie” for short.
                            </p>
                            <h5>Flat bar</h5>
                            <p>
                                A handlebar with little or no upward or downward curve; some flat bars will have a slight backward curve, or “sweep.”
                            </p>
                            <h5>Fork</h5>
                            <p>
                                The two-legged part of the frame that holds the front wheel in place. The steerer tube is a part of the fork that extends up into the frame through the head tube.
                            </p>
                            <h5>Frame</h5>
                            <p>
                                The main structural part of the bicycle, commonly made of steel, aluminum, titanium, or carbon fiber. Composed of a top tube, head tube, down tube, bottom bracket shell, seat tube, seat stays, and chain stays (see image). A frame and fork sold as a combination are referred to as a frameset.
                            </p>
                            <h5>Freehub body</h5>
                            <p>
                                A part of the hub on most rear wheels, it provides that coasting mechanism that transfers power to your wheel when you are pedaling forward, but allows the rear wheel to turn freely when you are pedaling backwards or not pedaling at all. The cassette is attached to the freehub body.
                            </p>
                            <h5>Freewheel</h5>
                            <p>
                                The collection of gears attached to the rear wheel found on mostly older bicycles and some lower-end modern bicycles. Both the gears and the coasting mechanism are part of the freewheel component, as opposed to cassette gears, where the gears are a solid, non-moving component, and the coasting mechanism is part of the wheel’s hub.
                            </p>
                            <h5>Headset</h5>
                            <p>
                                The collection of bearings housed within the head tube of the bike frame; it provides smooth steering.
                            </p>
                            <h5>Hub</h5>
                            <p>
                                The central component of a wheel; inside the hub are the axle and ball bearings.
                            </p>
                            <h5>Nipple</h5>
                            <p>
                                A small flanged nut that holds a spoke in place on the rim of a wheel. Turning the nipples with a spoke wrench is what allows the tension in the spokes to be adjusted, in order to "true" the wheel, i.e. make sure the wheel is perfectly round.

                            </p>
                            <h5>Rim</h5>
                            <p>
                                The outer "hoop" part of a wheel. Usually made of aluminum, although can be made of steel on some older or low-end bikes, or made of carbon fiber on some high-end racing bikes.
                            </p>
                            <h5>Rim strip or Rim tape</h5>
                            <p>
                                A layer of material, usually cloth, plastic, or rubber, that is installed around the outside of a rim (between the rim and inner tube), to prevent the ends of the spokes from puncturing the inner tube.
                            </p>
                            <h5>Riser bar</h5>
                            <p>
                                A type of handlebar with a "U" shape in the middle. Some riser bars have a very shallow "U" shape, like on some mountain bikes and most hybrid bikes, but some have a very deep "U" shape, like on some retro-style cruiser bikes.
                            </p>
                            <h5>Saddle</h5>
                            <p>
                                The preferred fancy word for "seat."
                            </p>
                            <h5>Seatpost</h5>
                            <p>
                                The rod that connects the saddle to the frame.
                            </p>
                            <h5>Seatpost clamp</h5>
                            <p>
                                The collar located at the top of the seat tube on the frame, which holds the seatpost at the desired height. Some seatpost clamps have a quick-release lever that allows for easy, tool-free adjustment, while others require a tool to tighten or loosen the clamp.
                            </p>
                            <h5>Stem</h5>
                            <p>
                                The part that connects the handlebar to the frame. Do not call this the "gooseneck," unless you want to make it perfectly clear that you are a clueless newbie. Stems come in two varieties, threadless--which clamps to the outside of the fork's steerer tube, and threaded, which is held in place by an expanding wedge bolt inside the fork's steerer tube.
                            </p>
                            <h5>Wheel</h5>
                            <p>
                                The complete assembly of hub, spokes, nipples, and rim.
                            </p>

                        </div><!-- end messagebox -->
                    </div><!-- end col -->
                </div><!-- end row -->


                <div class="row mt-5 pt-5">
                    <div class="col-md-12">
                        <div class="text-center">
                            <a class="sim-btn hvr-bounce-to-top" href="@Url.Action("Index", "Education")">
                                <i class="fa fa-long-arrow-left pr-2"></i>
                                <span>Back</span>
                            </a>
                        </div>
                    </div>
                </div>

            </div><!-- end container -->
        </div><!-- end section -->

    </div><!-- end container -->
</div><!-- end section -->

Views/Education/Index.cshtml
@{
    ViewBag.Title = "Education";
    ViewBag.BodyStyle = "body-no-banner";


}

<div id="portfolio" class="section lb">
    <div class="container">
        <div class="section-title text-center">
            <h3>Education</h3>
            <p>Something you need to know before start your riding.</p>
        </div><!-- end title -->

        <div class="gallery-menu row">
            <div class="col-md-12">
                <div class="button-group filter-button-group text-center">
                    <button class="active" data-filter="*">All</button>
                    <button data-filter=".gal_a">Road Rules</button>
                    <button data-filter=".gal_b">Bicycle Equipment</button>
                    <button data-filter=".gal_c">Traffic Signs</button>
                </div>
            </div>
        </div>


        <div class="gallery-list row">

            <div class="col-md-4 col-sm-6 gallery-grid gal_a gal_c">
                <a href="@Url.Action("Index", "StreetView")">
                    <div class="gallery-single fix">
                        <div class="post-box">
                            <div class="post-thumb">
                                <img src="~/Content/images/article_photo/photo_23.jpg" class="img-fluid" alt="post-img" />
                            </div>
                            <div class="post-info">
                                <h4>Road Signs on Street</h4>
                                <p>This page will give you insight of road sign place based on the street view</p>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <!--
                <div class="col-md-4 col-sm-6 gallery-grid gal_a">
                    <a href="@Url.Action("EssentialRoadRules", "Education")">
                        <div class="gallery-single fix">
                            <div class="post-box">
                                <div class="post-thumb">
                                    <img src="~/Content/images/article_photo/photo_01.jpg" class="img-fluid" alt="post-img" />
                                </div>
                                <div class="post-info">
                                    <h4>Essential Road Rules</h4>
                                    <p>As a bike rider you have to follow many of the same rules as Motorists. This section covers what they are so you can ride responsibly and safely.</p>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
        -->

            <div class="col-md-4 col-sm-6 gallery-grid gal_a">
                <a href="@Url.Action("RidingInTraffic", "Education")">
                    <div class="gallery-single fix">
                        <div class="post-box">
                            <div class="post-thumb">
                                <img src="~/Content/images/article_photo/photo_02.jpg" class="img-fluid" alt="post-img" />
                            </div>
                            <div class="post-info">
                                <h4>Riding in Traffic</h4>
                                <p>Here you can find out about the rules on riding on roads, overtaking, turning, crossings and trams.</p>
                            </div>
                        </div>
                    </div>
                </a>
            </div>

            <div class="col-md-4 col-sm-6 gallery-grid gal_a">
                <a href="@Url.Action("RidingLanesAndPaths", "Education")">
                    <div class="gallery-single fix">
                        <div class="post-box">
                            <div class="post-thumb">
                                <img src="~/Content/images/article_photo/photo_03.jpg" class="img-fluid" alt="post-img" />
                            </div>
                            <div class="post-info">
                                <h4>Riding on Bike Lanes and Paths</h4>
                                <p>It is important to know what bike lanes and paths look like and the different rules that apply to them.</p>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <!--
    <div class="col-md-4 col-sm-6 gallery-grid gal_b">
        <div class="gallery-single fix">
            <div class="post-box">
                <div class="post-thumb">
                    <img src="~/Content/images/article_photo/photo_04.png" class="img-fluid" alt="post-img" />
                </div>
                <div class="post-info">
                    <h4>Bikes and children</h4>
                    <p>Some different rules apply when you are riding with children.</p>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-4 col-sm-6 gallery-grid gal_b gal_c">
        <div class="gallery-single fix">
            <div class="post-box">
                <div class="post-thumb">
                    <img src="~/Content/images/article_photo/photo_05.png" class="img-fluid" alt="post-img" />
                </div>
                <div class="post-info">
                    <h4>Fines and crashes</h4>
                    <p>This section covers your responsibilities and rights if you break a road rule, are stopped by police or are involved in a crash.</p>
                </div>
            </div>
        </div>
    </div>


        <div class="col-md-4 col-sm-6 gallery-grid gal_a">
            <div class="gallery-single fix">
                <div class="post-box">
                    <div class="post-thumb">
                        <img src="~/Content/images/article_photo/photo_04.png" class="img-fluid" alt="post-img" />
                    </div>
                    <div class="post-info">
                        <h4>Bikes and children</h4>
                        <p>Some different rules apply when you are riding with children.</p>
                    </div>
                </div>
            </div>
        </div>
    -->

            <div class="col-md-4 col-sm-6 gallery-grid gal_b">
                <a href="@Url.Action("WearingHelmet", "Education")">
                    <div class="gallery-single fix">
                        <div class="post-box">
                            <div class="post-thumb">
                                <img src="~/Content/images/article_photo/photo_14.png" class="img-fluid" alt="post-img" />
                            </div>
                            <div class="post-info">
                                <h4>Wearing a Bicycle Helmet</h4>
                                <p>All bike and scooter riders are required to wear a bike helmet in Victoria.</p>
                            </div>
                        </div>
                    </div>
                </a>
            </div>

            <div class="col-md-4 col-sm-6 gallery-grid gal_b">
                <a href="@Url.Action("BikeComponents", "Education")">
                    <div class="gallery-single fix">
                        <div class="post-box">
                            <div class="post-thumb">
                                <img src="~/Content/images/article_photo/photo_16.jpg" class="img-fluid" alt="post-img" />
                            </div>
                            <div class="post-info">
                                <h4>Introduction: Bike Components for Beginners</h4>
                                <p>
                                    Buying a new bike or accessories can often be bewildering to the novice.
                                </p>
                            </div>
                        </div>
                    </div>
                </a>
            </div>


            <div class="col-md-4 col-sm-6 gallery-grid gal_a gal_c">
                <a href="@Url.Action("TrafficSigns", "Education")">
                    <div class="gallery-single fix">
                        <div class="post-box">
                            <div class="post-thumb">
                                <img src="~/Content/images/article_photo/photo_17.png" class="img-fluid" alt="post-img" />
                            </div>
                            <div class="post-info">
                                <h4>Traffic Signs</h4>
                                <p>Introduction of Australia traffic signs which related to bicycle.</p>
                            </div>
                        </div>
                    </div>
                </a>
            </div>


        </div>


        <div class="row mt-5">
            <div class="col-md-12">
                <div class="text-center">
                    <a class="sim-btn hvr-bounce-to-top" href="@Url.Action("Index", "Home")">
                        <i class="fa fa-long-arrow-left pr-2"></i>
                        <span>Back To Home</span>
                    </a>
                </div>
            </div>
        </div>

    </div>
</div>

Views/Education/RidingInTraffic.cshtml
@{
    ViewBag.Title = "RoadRules";
    ViewBag.BodyStyle = "body-no-banner";

}

<div id="article" class="section lb">
    <div class="container">
        <div class="section-title text-center">
            <h3>Education</h3>
            <p>Something you need to know before start your riding.</p>
        </div><!-- end title -->

        <div id="content" class="section wb">
            <div class="container">
                <div class="row mb-4">
                    <div class="col-md-1"></div>
                    <div class="col-md-7">
                        <div class="message-box">
                            <h2>Riding in Traffic</h2>
                            <p> by VicRoads </p>
                            <hr>
                            <h3>| Where you can ride</h3>
                            <p>
                                You can ride on the road unless there are signs saying otherwise, for example a ‘No
                                Bicycles’ sign or similar.
                            </p>
                            <h5>One lane of traffic</h5>
                            <p>
                                If there is only one lane heading where you want to go, you must ride as near as you can
                                to the far left side of the road where this is safe and practical.
                            </p>
                            <h5>Two or more lanes of traffic</h5>
                            <p>
                                When there are two or more lanes heading where you want to go (a multilane road), you
                                can ride on the left or down the centre of a lane and use the right-hand lane to do a right
                                turn.
                            </p>
                            <h5>Freeways</h5>
                            <p>
                                You can’t ride on urban freeways, but you can ride on the shoulders of some rural
                                freeways, including the Western Freeway, the Calder Freeway, the Hume Freeway and
                                parts of the Princes Freeway to Traralgon. The shoulder is an area to the left side of the
                                road, which can be sealed or unsealed.
                            </p>

                        </div><!-- end messagebox -->
                    </div><!-- end col -->

                    <div class="col-md-3">
                        <div class="wow fadeIn">
                            <img src="~/Content/images/article_photo/photo_11.png" alt="" class="img-fluid">
                        </div><!-- end media -->
                    </div><!-- end col -->
                </div><!-- end row -->


                <div class="row mb-4">
                    <div class="col-md-1"></div>
                    <div class="col-md-10">
                        <div class="tip">
                            <div class="tip-icon">
                                <i class="flaticon-innovation"></i>
                            </div>
                            <div class="tip-content">
                                <h3>Riding on the road</h3>
                                <p>
                                    When riding on the far left side of the road, leave enough space to deal with
                                    debris and the effects of wind, and to avoid car doors.
                                </p>
                            </div>
                        </div>
                    </div>
                </div><!-- end row -->


                <div class="row mb-4">
                    <div class="col-md-1"></div>
                    <div class="col-md-10">
                        <div class="message-box">
                            <h3>| Riding in groups</h3>
                            <p>
                                You cannot have more than two riders next to each other except when overtaking. When you are riding next to someone you must not ride more than 1.5 metres apart from them.
                            </p>
                            <h3>| Overtaking</h3>
                            <p>
                                When you are riding on the road, you can overtake a vehicle on the left or right as long
                                as:
                                <br> you can clearly see any approaching traffic and
                                <br>• can overtake the vehicle safely.
                                <br>
                                <br>You must not overtake a vehicle:
                                <br>• on the left if it is turning left and indicating left
                                <br>• on the right if it is turning right and indicating right
                                <br>• on the right if it is doing a U-turn from the centre of the road and indicating right.
                            </p>
                        </div><!-- end messagebox -->
                    </div><!-- end col -->
                </div><!-- end row -->

                <div class="row mb-4">
                    <div class="col-md-1"></div>
                    <div class="col-md-7">
                        <h3>Bike boxes</h3>
                        <p>
                            A bike box is a box marked at an intersection with a bike symbol inside it. Only bikes, not cars, can stop in a bike box, when the light is red (see image next page).
                            If there is a bike box, and you need to stop, you must stop inside it.
                            Bike boxes are a safer place to stop and give you a head start over other traffic when the traffic lights turn green.
                            If there is a bike lane leading into the bike box, you must use the bike lane to enter the bike box unless that is not a practical option.
                            If the bike box goes across all traffic lanes you must:
                            <br>• turn left from the left-lane side of the bike box
                            <br>• turn right from the right-lane side of the bike box.
                        </p>
                    </div>
                    <div class="col-md-3">
                        <div class="wow fadeIn">
                            <img src="~/Content/images/article_photo/photo_12.png" alt="" class="img-fluid">
                        </div><!-- end media -->
                    </div><!-- end col -->
                </div>


                <div class="row mt-5 pt-5">
                    <div class="col-md-12">
                        <div class="text-center">
                            <a class="sim-btn hvr-bounce-to-top" href="@Url.Action("Index", "Education")">
                                <i class="fa fa-long-arrow-left pr-2"></i>
                                <span>Back</span>
                            </a>
                        </div>
                    </div>
                </div>

            </div><!-- end container -->
        </div><!-- end section -->

    </div><!-- end container -->
</div><!-- end section -->